export const TRANSITION_ACTIONS = {
  SET_ACTIVE_INDEX: 'SET_ACTIVE_INDEX',
  SET_IS_TRANSITIONING: 'SET_IS_TRANSITIONING',
  RESET_STATE: 'RESET_STATE',
} as const;

export const TRANSITION_DURATION = 1000;
export const INTERVAL_DURATION = 20000; //  20sec